// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/clivern/beetle/internal/app/cmd"
	"github.com/clivern/beetle/internal/app/config"
)

func InitializeNewAPI() *cmd.API {
	config := config.NewConfig()
	cmdAPI := cmd.NewAPI(config)
	return cmdAPI
}
