---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beetle-configs
  namespace: default
data:
  config: |-
    ---
    version: 0.1.0

    applications:
      -
        name: Toad Nice Name
        id: toad
        image: clivern/toad:release-[.Version]
