---
apiVersion: v1
kind: ConfigMap
metadata:
  name: incluster-beetle-base-configs
  namespace: default
data:
  config: |-
    ---
    # App configs
    app:
        # Env mode (dev or prod)
        mode: ${BEETLE_APP_MODE:-prod}
        # HTTP port
        port: ${BEETLE_API_PORT:-8080}
        # App URL
        domain: ${BEETLE_APP_DOMAIN:-http://127.0.0.1:8080}
        # TLS configs
        tls:
            status: ${BEETLE_API_TLS_STATUS:-off}
            pemPath: ${BEETLE_API_TLS_PEMPATH:-cert/server.pem}
            keyPath: ${BEETLE_API_TLS_KEYPATH:-cert/server.key}

        # Message Broker Configs
        broker:
            # Broker driver (native)
            driver: ${BEETLE_BROKER_DRIVER:-native}
            # Native driver configs
            native:
                # Queue max capacity
                capacity: ${BEETLE_BROKER_NATIVE_CAPACITY:-5000}
                # Number of concurrent workers
                workers: ${BEETLE_BROKER_NATIVE_WORKERS:-4}

        # API Configs
        api:
            key: ${BEETLE_API_KEY:- }

        # Runtime, Requests/Response and Beetle Metrics
        metrics:
            prometheus:
                # Route for the metrics endpoint
                endpoint: ${BEETLE_METRICS_PROM_ENDPOINT:-/metrics}

        # Application Database
        database:
            # Database driver (sqlite3, mysql)
            driver: ${BEETLE_DATABASE_DRIVER:-sqlite3}
            # Database Host
            host: ${BEETLE_DATABASE_MYSQL_HOST:-localhost}
            # Database Port
            port: ${BEETLE_DATABASE_MYSQL_PORT:-3306}
            # Database Name
            name: ${BEETLE_DATABASE_MYSQL_DATABASE:-beetle.db}
            # Database Username
            username: ${BEETLE_DATABASE_MYSQL_USERNAME:-root}
            # Database Password
            password: ${BEETLE_DATABASE_MYSQL_PASSWORD:-root}

        # Kubernetes Clusters
        clusters:
            -
                name: ${BEETLE_KUBE_CLUSTER_01_NAME:-production}
                inCluster: ${BEETLE_KUBE_CLUSTER_01_IN_CLUSTER:-true}
                kubeconfig: ${BEETLE_KUBE_CLUSTER_01_CONFIG_FILE:- }
                configMapName: ${BEETLE_KUBE_CLUSTER_01_CONFIG_MAP:-beetle-configs}

        # HTTP Webhook
        webhook:
            url: ${BEETLE_WEBHOOK_URL:- }
            retry: ${BEETLE_WEBHOOK_RETRY:-3}
            apiKey: ${BEETLE_WEBHOOK_API_KEY:- }

    # Log configs
    log:
        # Log level, it can be debug, info, warn, error, panic, fatal
        level: ${BEETLE_LOG_LEVEL:-info}
        # output can be stdout or abs path to log file /var/logs/beetle.log
        output: ${BEETLE_LOG_OUTPUT:-stdout}
        # Format can be json
        format: ${BEETLE_LOG_FORMAT:-json}
